version: "3.7"
name: badminton-booking-alarm

services:
  badminton-booking-alarm-dynamodb-local:
    image: amazon/dynamodb-local
    container_name: badminton-booking-alarm-dynamodb-local
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-optimizeDbBeforeStartup", "-dbPath", "/data/dynamodb"]
    volumes:
      - ./data/dynamodb:/data/dynamodb
    ports:
      - $DYNAMODB_PORT:8000

  badminton-booking-alarm-dynamodb-admin:
    platform: linux/amd64
    image: badminton-booking-alarm-dynamodb-admin
    container_name: badminton-booking-alarm-dynamodb-admin
    environment:
      - AWS_REGION=ap-southeast-2
      - DYNAMO_ENDPOINT=http://badminton-booking-alarm-dynamodb-local:8000
      - DYNAMO_ADMIN_UI_PORT
    build:
      context: ./infra/dynamodbAdmin
    ports:
      - $DYNAMO_ADMIN_UI_PORT:3500

  # repository name must be lowercase
  badminton-booking-alarm-event-bridge:
    platform: linux/amd64
    image: badminton-booking-alarm-event-bridge
    container_name: badminton-booking-alarm-event-bridge
    build:
      context: ./infra/eventBridge
    ports:
      - 5618:5208

  badminton-booking-alarm-booking-service:
    image: badminton-booking-alarm-booking-service
    container_name: badminton-booking-alarm-booking-service
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env.docker
    volumes:
      - ~/.aws/:/root/.aws/
    ports:
      - 3000:8194
